### ISSUE TITLE
Continued development.

### ISSUE THREAD

**Issue by JimBobSquarePants** [Pathfoundry-PTY-LTD/LinFu.DynamicProxy#1]
Hi there,

Trying not to be that "Is this dead" guy but I wanted to ask as to whether you are still actively developing the code. I've spotted a bug whilst going through the codebase and some possible performance improvements also and I was wondering whether I should take the time to submit some pull requests.

Cheers

James

**Comment by philiplaureano** [comment]
Hi James,

I'll keep doing LinFu dev as long as someone needs it. It was the first OSS
project that changed my life, so I won't abandon it any time soon.

Regards,

Philip Laureano

**Comment by JimBobSquarePants** [comment]
Hi Philip,

Excellent! That's a very commendable attitude to have by the way. :smile:  I'll send some code your way soon.

Cheers

James

**Comment by philiplaureano** [comment]
Wow, talk about timely development :D I just saw your tweet today and found your message.

**Comment by philiplaureano** [comment]
3 years later, and LinFu.DynamicProxy now supports .NET Standard 2.0, with very little changes. Have a look at it and let me know what you think. 👍
